os: linux
dist: bionic
language: ruby
rvm: 2.7.0

addons:
  apt:
    packages:
      - libcurl4-openssl-dev  # to avoid SSL error (for htmlproofer)

# Overriding to drop the `--development` flag which requires the Gemfile.lock at build
install: bundle install --jobs=3 --retry=3 --path=vendor/bundle

before_script: git -C "$HOME" clone "$BUILDER_REPO" --depth=1 -q

jobs:
  include:
    - stage: Upgrade
      git:
        depth: false  # for posts' lastmod
      script: eval "$BUILD_CMD"
    - stage: Starter
      language: minimal
      install: true   # skip install step
      script: eval "$FLUSH_STARTER"
    - stage: Docs
      cache: bundler
      git:
        depth: false  # for posts' lastmod
      script: eval "$DOCS_CMD"

stages:
  - name: Upgrade
    if: branch =~ /^v(\d)+(\.(\d)+){2}$/ OR tag IS present
  - name: Starter
    if: branch =~ /^v(\d)+(\.(\d)+){2}$/ OR tag IS present
  - name: Docs
    if: branch = docs


env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
